#!/bin/sh
##############################################################
# chkconfig: 345 98 98
### BEGIN INIT INFO
# Provides: DHCPReplicator
# Required-Start: $local_fs $network $remote_fs
# Required-Stop: $local_fs $network $remote_fs
# Default-Start:  3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop the DHCP replicator
# Description: Copies LibVirt DHCP leases into DNS
### END INIT INFO


JSVC=/usr/bin/jsvc
RUN_AS_USER=dhcpreplicator
PID_FILE=/var/run/dhcpreplicator.pid
LOG_FILE=/var/log/dhcpreplicator.out

REPLICATOR_HOME=/usr/local/share/dhcpreplicator

CLASSPATH='.:$JAVA_HOME/lib/tools.jar'
for LIB in $REPLICATOR_HOME/lib/*
do
    CLASSPATH=$CLASSPATH:$LIB
done

MAIN_CLASS=com.davidtrott.util.dns.replicator.DhcpDaemon

case "$1" in
  start)
    echo $"Starting DHCP Replicator..."
    cd $REPLICATOR_HOME && $JSVC -user $RUN_AS_USER -home $JAVA_HOME -wait 3 -pidfile $PID_FILE -outfile $LOG_FILE -errfile '&1' -cp $CLASSPATH $MAIN_CLASS
    exit $?
  ;;

  stop)
    echo $"Stoping DHCP Replicator..."
    $JSVC -user $RUN_AS_USER -stop -pidfile $PID_FILE $MAIN_CLASS
    exit $?
  ;;

  restart)
    $0 stop
    $0 start
    exit $?
  ;;

  *)
    echo "Usage: dhcpreplicator {start|stop}"
    exit 1;;
esac
